version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "80:80"
    links:
      - postgres:postgres
    volumes:
      - ./web:/web
    env_file: .env
    environment:
      DEBUG: 'true'
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:80"

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:

